name: Build
# Need GitHub secret: CODECOV_TOKEN

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
    branches:
      - 'master'

jobs:
  UnitTest:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.18
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Test
        run: |
          go test ./... -coverprofile cover.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true